# -*- coding: utf-8 -*-
"""Phase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vaBNbsdjtde1uL5FW-aNXqYnIaDKdPqZ
"""

from google.colab import drive
drive.mount('/content/drive')

import os
IMG_FOLDER = '/content/drive/MyDrive/NLP driven Invoice Management System/invoice images'

print('Found', len(os.listdir(IMG_FOLDER)), 'files')

#installing dependencies
!pip install pytesseract pillow transformers
#pytesseract for Optical Character Recognition(OCR)
#pillow to open image files
#transformers to use pre-trained transformer models

!apt update
!apt install tesseract-ocr
!tesseract --version

#lets check whether we can read images and extract text using ocr
from PIL import Image
import pytesseract
import os

def ocr_image(image_path):
    img = Image.open(image_path)
    text = pytesseract.image_to_string(img)
    return text

#lets check one sample image
sample_image_path = os.path.join(IMG_FOLDER, os.listdir(IMG_FOLDER)[0])
print("Sample image path:", sample_image_path)

text = ocr_image(sample_image_path)
print("Extracted text:\n", text)

# Empty list to store extracted data
data = []

# Loop over all images
for i, fname in enumerate(os.listdir(IMG_FOLDER)):
    image_path = os.path.join(IMG_FOLDER, fname)
    text = ocr_image(image_path)
    data.append({'filename': fname, 'extracted_text': text})

    if i % 100 == 0:
        print(f"Processed {i} images...")

# Convert to DataFrame
import pandas as pd
df = pd.DataFrame(data)

# Save as csv
csv_path = '/content/drive/MyDrive/NLP driven Invoice Management System/Phase 1 Output/invoice_texts.csv'
os.makedirs(os.path.dirname(csv_path), exist_ok=True)
df.to_csv(csv_path, index=False)
print(f"CSV saved to {csv_path}")